export enum EMovieCategory {
  ACAO = 'acao',
  COMEDIA = 'comedia',
  DRAMA = 'drama',
  TERROR = 'terror',
  ROMANCE = 'romance',
  FANTASIA = 'fantasia',
  SUSPENSE = 'suspense',
  CRIME = 'crime',
  ANIME = 'anime',
  DORAMAS = 'doramas',
  DOCUMENTARIO = 'documentario',
  NETFLIX = 'netflix',
  PRIME_VIDEO = 'prime-video',
  DISNEY = 'disney',
  MAX = 'max',
  APPLE_TV = 'apple-tv',
  PARAMOUNT = 'paramount',
  GLOBOPLAY = 'globoplay',
  CRUNCHYROLL = 'crunchyroll',
}

export enum EMovieCategoryLabel {
  ACAO = 'Ação',
  COMEDIA = 'Comédia',
  DRAMA = 'Drama',
  TERROR = 'Terror',
  ROMANCE = 'Romance',
  FANTASIA = 'Fantasia',
  SUSPENSE = 'Suspense',
  CRIME = 'Crime',
  ANIME = 'Anime',
  DORAMAS = 'Doramas',
  DOCUMENTARIO = 'Documentário',
  NETFLIX = 'Netflix',
  PRIME_VIDEO = 'Prime Video',
  DISNEY = 'Disney+',
  MAX = 'Max',
  APPLE_TV = 'Apple TV+',
  PARAMOUNT = 'Paramount+',
  GLOBOPLAY = 'Globoplay',
  CRUNCHYROLL = 'Crunchyroll',
}
